version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 15
    commands:
      - echo "Node version:"
      - node -v
      - echo "Installing dependencies"
      - npm install

  build:
    commands:
      - echo "Running lint"
      - npm run lint

      - echo "Fixing formatting"
      - npx prettier --write ./src/

      - echo "Running tests"
      - CI=true npm run test -- --watchAll=false

      - echo "Building project"
      - npm run build

artifacts:
  files:
    - '**/*'