version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Node version:
      - node -v
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Running lint...
      - npm run lint
      - echo Running formatter...
      - npm run prettier
      - echo Running tests...
      - npm run test
      - echo Building project...
      - npm run build

artifacts:
  files:
    - '**/*'