name: CD Pipeline

on:
  push:
    branches:
      - devel
      - stage

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: terraform/envs/${{ github.ref_name }}

      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform/envs/${{ github.ref_name }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform/envs/${{ github.ref_name }}
